#! /bin/sh

# This is a script used for executing scripts, sourcing softwares and other
# things before starting a terminal. These are not related to bash or zsh and 
# thus kept in a seperate file.

export TERM=xterm-256color

# Anaconda3 stuff
# export PATH="/home/dharmin/anaconda3/bin:$PATH"
source /home/dharmin/anaconda3/etc/profile.d/conda.sh

# ROS stuff 
export ROBOT_ENV=empty-world
export ROBOT=youbot-brsu-arm
# export ROBOT_ENV=brsu-c025-sim
# export ROBOT=youbot-brsu-1

# use the previously chose catkin workspace
source $(cat ~/.config/catkin_workspace/chosen_catkin_workspace)

# ranger file browser related settings
export RANGER_LOAD_DEFAULT_RC=FALSE
VISUAL=vim; export VISUAL EDITOR=vim; export EDITOR

# neofetch on start
neofetch --source ~/.config/neofetch/batman3
