" =============================================================================
" General settings
" =============================================================================

set confirm

" change cursor in different modes
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" setting to keep cursor line in middle
set scrolloff=5

" Vim loads indentation and plugins acc. to detected filetype
filetype plugin indent on

" Vim jumps to last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Better copy & paste
set pastetoggle=<F2>
set clipboard=unnamedplus

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

" Enable backspace to work normally
set backspace=start,eol,indent

" Enable syntax highlighting
syntax on

" make hidden characters like tabs or EOL visible
" set listchars=nbsp:_,trail:.,tab:▸\ ,eol:¬
set listchars=nbsp:_,trail:.,tab:▸\ 
set list

" disable auto-commenting when entering new line
autocmd FileType * setlocal formatoptions+=c formatoptions+=r formatoptions-=o

" enter the current millenium
set nocompatible

" hide buffers instead of closing when switching to another buffer
set hidden

" use every file in current dir and child dir while "find" ind
set path=**

" wildmenu for fuzzy file finding
set wildmenu

" level of nesting to fold
" set foldnestmax=0
set nofoldenable
" set foldlevel=0

" Show line numbers
set number

" Show relative line numbers
" set relativenumber

" Set tabs width to 4, it is still \t
set tabstop=4
" Set shiftwidth to 0 which makes it equal to tabwidth by default. This is
" needed to use proper indentation
set shiftwidth=0

" Expand tabs into spaces
set expandtab|retab

" Indent when moving to the next line while writing code
set autoindent

" setting smart indentation
set smartindent

" Show the matching part of the pair for [] {} and ()
set showmatch

" set color column
hi ColorColumn ctermbg=darkgrey guibg=lightgrey
set colorcolumn=80
" set textwidth
set textwidth=80
" disable autowrap text when writing in insert mode
set formatoptions-=t
" disable wrapping the lines
set nowrap

" highlight search
set hlsearch

" include search (highlights while typing the search pattern)
set incsearch
" Make search case insensitive
set ignorecase
set smartcase

" Disable backup and swap files
set nobackup
set nowritebackup
set noswapfile

" Eliminate delay between INSERT and ESCAPE
set timeoutlen=1000 ttimeoutlen=0

" show pressed normal mode commands
set showcmd



" =============================================================================
" Key Mappings
" =============================================================================

" map spacebar as leader key
nnoremap <space> <nop>
let mapleader=" "

" my mappings
:command! W w
:command! Q q
:command! WQ wq
:command! Wq wq
:command! Toc VimtexTocOpen
:command! RemoveWhiteSpace %s/\s\+$//e

" Mouse click
" set mouse=a
" disable scroll using mouse
nmap <ScrollWheelUp> <nop>
nmap <ScrollWheelDown> <nop>
imap <ScrollWheelUp> <nop>
imap <ScrollWheelDown> <nop>
vmap <ScrollWheelUp> <nop>
vmap <ScrollWheelDown> <nop>

" Copy in the clipboard
vnoremap <C-c> "+y
vnoremap <C-v> "+p

" Easier indentation of code blocks
vnoremap < <gv
vnoremap > >gv

" Move between splits
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>l :wincmd l<CR>

" open directory tree on left side
nnoremap <leader>e :20Lexplore<CR>

" search for selected text
vnoremap // y/<C-R>"<CR>

" Y behave like other uppercase letters
nnoremap Y y$

" remove search highlight
nnoremap <leader>n :noh<CR>



" =============================================================================
" Plugins
" =============================================================================

" Automatically download vim-plug if not present
let data_dir = '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

colorscheme onedark

" source all plugins
call plug#begin(data_dir . '/plugged')
source ~/.vim/plugins/ultisnips.vim
source ~/.vim/plugins/vim-snippets.vim
source ~/.vim/plugins/vim-commentary.vim
source ~/.vim/plugins/vim-fugitive.vim
source ~/.vim/plugins/vim-surround.vim
source ~/.vim/plugins/vim-cpp-enhanced-highlight.vim
source ~/.vim/plugins/fzf.vim
source ~/.vim/plugins/lightline.vim
source ~/.vim/plugins/vim-hardtime.vim
source ~/.vim/plugins/quick-scope.vim
source ~/.vim/plugins/vimtex.vim
source ~/.vim/plugins/DoxygenToolkit.vim
source ~/.vim/plugins/vim-markdown.vim
call plug#end()


source ~/.vim/plugins/my_autocomplete.vim
source ~/.vim/plugins/switch_source_header.vim
source ~/.vim/plugins/netrw_settings.vim
source ~/.vim/plugins/tag_managment.vim
source ~/.vim/plugins/terminal_build.vim
source ~/.vim/plugins/quick_switch.vim


" =============================================================================
" Color scheme
" =============================================================================
" set background=dark
" transparent background
hi Normal guibg=NONE ctermbg=NONE
